services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    container_name: password-vault-api
    ports:
      - "8020:8020"
    env_file:
      - ./backend/.env
    deploy:
      resources:
        limits:
          memory: 250M
          cpus: 1
        reservations:
          memory: 128M
