// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasswordVault.Common.Database;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926192744_AlignWebsiteTablesWithErd")]
    partial class AlignWebsiteTablesWithErd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasswordVault.Common.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sys_user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LastNameFer")
                        .HasColumnType("varchar(420)")
                        .HasColumnName("sys_user_last_name_fer");

                    b.Property<string>("NameFer")
                        .HasColumnType("varchar(420)")
                        .HasColumnName("sys_user_name_fer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("sys_user_password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsernameFer")
                        .IsRequired()
                        .HasColumnType("varchar(420)")
                        .HasColumnName("sys_user_username_fer");

                    b.Property<string>("UsernameSha")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sys_user_username_sha");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("sys_user_uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("isTemporal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporal");

                    b.HasKey("Id");

                    b.ToTable("sys_user", "public");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.UserWebsiteCredentialModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_website_credential_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool?>("IsSecure")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secure");

                    b.Property<string>("PasswordFer")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_credential_password_fer");

                    b.Property<string>("PasswordSha")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_website_credential_password_sha");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsernameFer")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_credential_username_fer");

                    b.Property<string>("UsernameSha")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("user_website_credential_username_sha");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_credential_uuid")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_website_id");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId");

                    b.ToTable("user_website_credential", "public");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.UserWebsiteLinkModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_website_link_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_link_url");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_link_uuid")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<long>("WebsiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_website_id");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId");

                    b.ToTable("user_website_link", "public");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.WebsiteModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_website_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("sys_user_id");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_uuid");

                    b.Property<string>("WebsiteName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("user_website_name");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_website", "public");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.UserWebsiteCredentialModel", b =>
                {
                    b.HasOne("PasswordVault.Common.Models.WebsiteModel", "Website")
                        .WithMany("Credentials")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.UserWebsiteLinkModel", b =>
                {
                    b.HasOne("PasswordVault.Common.Models.WebsiteModel", "Website")
                        .WithMany("Links")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.WebsiteModel", b =>
                {
                    b.HasOne("PasswordVault.Common.Models.UserModel", "User")
                        .WithMany("Websites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.UserModel", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("PasswordVault.Common.Models.WebsiteModel", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
